wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.8
    start_time: 1647616433
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 13
      - 16
      4: 3.9.8
      5: 0.12.11
      8:
      - 5
alpha:
  desc: null
  value: 0.99
baseline_cost:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 24
demb:
  desc: null
  value: 30
disable_checkpoint:
  desc: null
  value: false
disable_cuda:
  desc: null
  value: false
discounting:
  desc: null
  value: 0.99
drep:
  desc: null
  value: 400
drnn:
  desc: null
  value: 100
drnn_small:
  desc: null
  value: 10
entropy_cost:
  desc: null
  value: 0.0006
env:
  desc: null
  value: groups_simple_stationary-v0
epsilon:
  desc: null
  value: 0.01
height:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0014
max_inv:
  desc: null
  value: 8
max_name:
  desc: null
  value: 8
max_placement:
  desc: null
  value: 1
max_task:
  desc: null
  value: 40
max_wiki:
  desc: null
  value: 80
mode:
  desc: null
  value: train
model:
  desc: null
  value: paper_txt2pi
momentum:
  desc: null
  value: 0
num_actors:
  desc: null
  value: 20
num_buffers:
  desc: null
  value: 40
num_threads:
  desc: null
  value: 4
partial_observability:
  desc: null
  value: false
prefix:
  desc: null
  value: default
pretrained_emb:
  desc: null
  value: false
queue_timeout:
  desc: null
  value: 1
random_agent:
  desc: null
  value: false
resume:
  desc: null
  value: null
resume_scheduler:
  desc: null
  value: false
resume_strategy:
  desc: null
  value: all
reward_clipping:
  desc: null
  value: abs_one
savedir:
  desc: null
  value: checkpoints
shuffle_wiki:
  desc: null
  value: false
time_penalty:
  desc: null
  value: -0.02
total_frames:
  desc: null
  value: 10000
unroll_length:
  desc: null
  value: 80
width:
  desc: null
  value: 6
wiki:
  desc: null
  value: 'yes'
xpid:
  desc: null
  value: groups_simple_stationary:paper_txt2pi:yeswiki:default
